spring:
  datasource:
    url: jdbc:mysql://localhost:5100
    username: root
    password: practice
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: false
    database: MYSQL
    generate-ddl: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_catalog: main
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul

logging.level:
  ROOT: INFO
  net.inbon: DEBUG
  org.hibernate.SQL: INFO
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener: ERROR
